"""T2 -- optimized offline feature computation into the two Gold Delta tables (guide s4).

Gate: **G3 Atomicity** -- "failed run khong de committed partial output" (guide s13). G3 is the
gate this module owns, but every later gate reads what it writes, so its declared surface is the
foundation for G1/G2/G4/G5/G6/G7/G9/G10 as well.

Guide s4.0 fixes two artifacts from one contract, and they are NOT interchangeable:

* ``pre_decision_features`` -- the aggregate immediately *before* each transaction. Training reads
  it (T4), and it is also the table Feast's ``FeatureView`` serves (guide s3.2.1), so T1 and T2
  have a real dependency.
* ``post_event_state_updates`` -- the aggregate *after* consuming each transaction. T5 materializes
  it into the online store. Guide s4.0: never materialize the latest ``pre_decision_features`` row,
  because it excludes the newest transaction and leaves online state one event behind.

Both are generated from the same FeatureSpec/reducer, and a fixture must prove the shift relation
between them (guide s4.0). The relation this module declares is
:data:`GOLD_SHIFT_RELATION` -- see it for the exact statement and its limits.

Two traps carried over from T1. They are written here because T2 repeats both at full scale.

**Trap 1 -- the feature table must be computed by the SQL ENGINE, never by the oracle.**
``features/paysim_recipient.py: paysim_pre_decision_feature_sql`` is the engine; it is imported,
never restated. ``features/paysim_reference.py`` is the pure-Python oracle and it is the
*expectation*, never the producer. A Gold table generated by the oracle and then compared against
the oracle is a tautology -- it checks one derivation against itself and G1/G3 would pass while
proving nothing. Two independent derivations (a DuckDB range self-join with ``DECIMAL(18,2)``
aggregation on one side, explicit ``decimal.Decimal`` loops on the other) is the only arrangement
in which agreement is evidence. Direction of authority when they disagree: the SQL is wrong until
proven otherwise (``paysim_reference.py`` module docstring). Never edit the expectation onto the
output.

**Trap 2 -- timestamps are computed in PYTHON, never in SQL.** ``event_timestamp`` and
``created_timestamp`` are the ADR-006 affine map of ``step``/``knowledge_step`` from
``EPOCH_0 = 2020-01-01T00:00:00Z``, and the single implementation is
``features/paysim_specs.py: paysim_step_to_timestamp`` (ADR-006 decision 1.7 -- exactly one
implementation, the constant is never re-typed). A DuckDB ``TIMESTAMPTZ`` expression renders
against the *session* time zone, so computing them in SQL makes the committed bytes depend on
which machine ran the build. Append them in Python, after the engine has produced the row.

Neither derived column is ever an input to the PIT computation. Eligibility, window bounds and the
replay tie-break stay on the integer ordinals ``(step, source_row_number)`` -- ADR-006 decision 1.4:
hour-resolution timestamps cannot express the tie-break at all, because every row in one ``step``
maps to the same instant.

Round-0 status: signatures, schemas and acceptance criteria only. Every body raises
``NotImplementedError``.
"""

from __future__ import annotations

import hashlib
import json
import time
from dataclasses import asdict, dataclass, replace
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Final, Literal

import duckdb
import pyarrow as pa
import pyarrow.dataset as ds
from deltalake import DeltaTable, write_deltalake

from pit_fintech.contracts.manifests import ApplicationLakehouseManifest
from pit_fintech.data.paysim_lakehouse import (
    arrow_schema_checksum,
    find_latest_paysim_lakehouse_manifest,
)
from pit_fintech.features.paysim_recipient import (
    PAYSIM_PRE_DECISION_SOURCE_COLUMNS,
    paysim_pre_decision_feature_sql,
)
from pit_fintech.features.paysim_reference import (
    PaySimSourceEvent,
    compute_paysim_feature_vectors,
)
from pit_fintech.features.paysim_specs import (
    PAYSIM_AMOUNT_DECIMAL_TYPE,
    PAYSIM_ENTITY,
    PAYSIM_ENTITY_DEFINITION_VERSION,
    PAYSIM_FEATURE_DEFINITION_VERSION,
    PAYSIM_FEATURE_SERVICE_VERSION,
    PAYSIM_HISTORY_FEATURE_NAMES,
    PAYSIM_MODEL_FEATURE_ORDER,
    paysim_feature_contract_checksum,
    paysim_step_to_timestamp,
)
from pit_fintech.platform.lineage import (
    COMPONENT_FINGERPRINT_POLICY_VERSION,
    component_dirty,
    component_fingerprint,
    current_git_commit,
    repository_dirty,
)

if TYPE_CHECKING:  # pragma: no cover - annotations only
    import duckdb

# --------------------------------------------------------------------------------------------
# Table identity and layout
# --------------------------------------------------------------------------------------------

GOLD_BUILDER_PIPELINE_VERSION: Final = "paysim-gold-v1"
GOLD_COMPONENT_PATHS: Final = (
    "src/pit_fintech/features/build_offline.py",
    "src/pit_fintech/features/paysim_recipient.py",
    "src/pit_fintech/features/paysim_reference.py",
    "src/pit_fintech/features/paysim_specs.py",
    "src/pit_fintech/data/paysim_lakehouse.py",
    "src/pit_fintech/platform/lineage.py",
    "pyproject.toml",
    "uv.lock",
)

#: Delta table names, frozen by guide s4.0. Downstream modules import these; they never re-type
#: the strings.
GOLD_PRE_DECISION_TABLE: Final = "pre_decision_features"
GOLD_POST_EVENT_TABLE: Final = "post_event_state_updates"
GOLD_LAYER: Final = "gold"

#: Path layout, continuing exactly the convention `data/paysim_lakehouse.py` established for
#: Bronze/Silver: ``<data_root>/lakehouse/paysim1/<raw_sha256[:16]>/<layer>/<table>``.
#: `paysim_lakehouse.build_paysim_lakehouse` derives `snapshot_prefix` the same way, so a Gold
#: table always sits beside the exact Silver version it was built from.
GOLD_PATH_TEMPLATE: Final = "{data_root}/lakehouse/paysim1/{snapshot_prefix}/gold/{table}"

#: Guide s4.3 staging root. A run writes here first and is promoted only after every validation in
#: :data:`GOLD_PROMOTION_PRECONDITIONS` passes.
GOLD_STAGING_PATH_TEMPLATE: Final = "{artifact_root}/runs/{run_id}/staging/{table}"

#: Partition column, identical in name, type and expression to Bronze/Silver
#: (``floor((step - 1) / 24.0)::INTEGER + 1``, `paysim_lakehouse._event_day_sql`). It is an integer
#: day ordinal, NOT a date: ADR-006 decision 1.2 forbids presenting derived PaySim time as a
#: business calendar. Partitioning on it is what makes guide s4.2's "read only the partitions
#: needed for the output range plus the lookback window" expressible as a pruning predicate.
GOLD_PARTITION_COLUMN: Final = "event_day"
#: PaySim1's frozen maximum step. The final event-day partition is partial (steps 721-743).
GOLD_MAX_STEP: Final = 743

#: The widest history window, in hour ordinals. An output range ``[start, end]`` must read source
#: partitions covering ``[start - GOLD_LOOKBACK_STEPS, end]`` and no more (guide s4.2, s5.3).
GOLD_LOOKBACK_STEPS: Final = 168


@dataclass(frozen=True, slots=True)
class GoldColumn:
    """One frozen Gold column: name, exact Arrow type, nullability."""

    name: str
    arrow_type: str
    nullable: bool


# --------------------------------------------------------------------------------------------
# Schema 1: gold.pre_decision_features
# --------------------------------------------------------------------------------------------

#: One row per **in-scope cutoff** -- ``CASH_OUT``/``TRANSFER`` with a ``CUSTOMER`` destination
#: (ADR-003 scoring scope). Rows outside the scope stay pipeline data and never appear here.
#:
#: Column order is frozen. Columns 1-16 are byte-identical in name, order and type to
#: ``data/paysim_fixture.py: PAYSIM_FEATURE_TABLE_COLUMNS`` -- the shape T1's Feast `FileSource`
#: already binds to -- so the full-scale table is a superset of the fixture, never a different
#: shape. See :data:`GOLD_FEAST_SOURCE_COLUMNS`.
#:
#: Columns 17-20 are the additions T2 needs and the fixture deliberately dropped. ``step`` and
#: ``knowledge_step`` are back because they are the *ordering authority*: the T4 temporal split is
#: on step ranges (ADR-002 decision 7: 1-520/521-631/632-743) and the T6 replay order is
#: ``(step, source_row_number)`` (ADR-002 decision 2). ADR-006 decision 1.4 requires the ordering
#: to stay on the integer columns, so the table that training and replay read has to carry them.
#: A consumer must still never join on them where Feast validates on the timestamps.
PRE_DECISION_FEATURE_SCHEMA: Final[tuple[GoldColumn, ...]] = (
    GoldColumn(PAYSIM_ENTITY, "string", False),
    GoldColumn("event_timestamp", "timestamp[us, tz=UTC]", False),
    GoldColumn("created_timestamp", "timestamp[us, tz=UTC]", False),
    GoldColumn("current_amount", "double", False),
    GoldColumn("event_step", "double", False),
    GoldColumn("transaction_type_transfer", "double", False),
    GoldColumn("pit_prior_count_1h", "int64", False),
    GoldColumn("pit_prior_amount_1h", "double", False),
    GoldColumn("recipient_has_history_1h", "int64", False),
    GoldColumn("pit_prior_count_24h", "int64", False),
    GoldColumn("pit_prior_amount_24h", "double", False),
    GoldColumn("recipient_has_history_24h", "int64", False),
    GoldColumn("pit_prior_count_168h", "int64", False),
    GoldColumn("pit_prior_amount_168h", "double", False),
    GoldColumn("recipient_has_history_168h", "int64", False),
    GoldColumn("source_row_number", "int64", False),
    GoldColumn("step", "int64", False),
    GoldColumn("knowledge_step", "int64", False),
    GoldColumn("transaction_type", "string", False),
    GoldColumn(GOLD_PARTITION_COLUMN, "int32", False),
)

#: The projection a Feast `FileSource` reads, in exactly the order
#: `feature_repo/definitions.py` already binds to via
#: ``data/paysim_fixture.py: PAYSIM_FEATURE_TABLE_COLUMNS``. Selecting this tuple out of
#: :data:`PRE_DECISION_FEATURE_SCHEMA` must reproduce the fixture table's schema exactly.
GOLD_FEAST_SOURCE_COLUMNS: Final[tuple[str, ...]] = (
    PAYSIM_ENTITY,
    "event_timestamp",
    "created_timestamp",
    *PAYSIM_MODEL_FEATURE_ORDER,
    "source_row_number",
)

# --------------------------------------------------------------------------------------------
# Schema 2: gold.post_event_state_updates
# --------------------------------------------------------------------------------------------

#: The nine post-event state field names, in the same window order as
#: ``PAYSIM_HISTORY_FEATURE_NAMES``, but under a ``post_`` prefix.
#:
#: The rename is a **leakage guard, not cosmetics**. If post-event state carried the contract's own
#: field names, a training job pointed at the wrong Gold table would silently train on
#: current-inclusive aggregates -- which is precisely experiment E2, the deliberately leaky positive
#: control (ADR-003 context table, PR-AUC 0.915528 against E4's 0.324524). With distinct names that
#: mistake is a ``KeyError`` at read time instead of an impressive-looking metric. T5 maps these
#: onto the twelve contract names when it writes the online record, and that mapping is
#: :data:`POST_EVENT_TO_CONTRACT_FIELD` -- the single place the two vocabularies meet.
POST_EVENT_STATE_FIELD_NAMES: Final[tuple[str, ...]] = (
    "post_count_1h",
    "post_amount_1h",
    "post_has_history_1h",
    "post_count_24h",
    "post_amount_24h",
    "post_has_history_24h",
    "post_count_168h",
    "post_amount_168h",
    "post_has_history_168h",
)

#: post-event state field -> the contract history field it becomes when T5 writes an online record.
#: Positional pairing against ``PAYSIM_HISTORY_FEATURE_NAMES``; asserted at import.
POST_EVENT_TO_CONTRACT_FIELD: Final[dict[str, str]] = {
    "post_count_1h": "pit_prior_count_1h",
    "post_amount_1h": "pit_prior_amount_1h",
    "post_has_history_1h": "recipient_has_history_1h",
    "post_count_24h": "pit_prior_count_24h",
    "post_amount_24h": "pit_prior_amount_24h",
    "post_has_history_24h": "recipient_has_history_24h",
    "post_count_168h": "pit_prior_count_168h",
    "post_amount_168h": "pit_prior_amount_168h",
    "post_has_history_168h": "recipient_has_history_168h",
}

#: One row per **source event**, not per in-scope cutoff. Online state has to move on every event
#: that touches a destination, whatever its transaction type, because history counts every prior
#: event to that destination regardless of type (``paysim_reference.in_scoring_scope`` docstring;
#: the SQL ``scoped_history`` CTE does the same). Restricting this table to the scoring scope would
#: make online state disagree with offline history for every destination that ever received a
#: ``CASH_IN``, ``DEBIT`` or ``PAYMENT``.
#:
#: There are no request-time fields here. ``current_amount``/``event_step``/
#: ``transaction_type_transfer`` describe the request being scored, not the state of an entity; T7
#: derives them from the request itself (guide s9.3 step 2).
POST_EVENT_STATE_SCHEMA: Final[tuple[GoldColumn, ...]] = (
    GoldColumn(PAYSIM_ENTITY, "string", False),
    GoldColumn("event_timestamp", "timestamp[us, tz=UTC]", False),
    GoldColumn("created_timestamp", "timestamp[us, tz=UTC]", False),
    GoldColumn("post_count_1h", "int64", False),
    GoldColumn("post_amount_1h", "double", False),
    GoldColumn("post_has_history_1h", "int64", False),
    GoldColumn("post_count_24h", "int64", False),
    GoldColumn("post_amount_24h", "double", False),
    GoldColumn("post_has_history_24h", "int64", False),
    GoldColumn("post_count_168h", "int64", False),
    GoldColumn("post_amount_168h", "double", False),
    GoldColumn("post_has_history_168h", "int64", False),
    GoldColumn("source_row_number", "int64", False),
    GoldColumn("step", "int64", False),
    GoldColumn("knowledge_step", "int64", False),
    GoldColumn("transaction_type", "string", False),
    GoldColumn(GOLD_PARTITION_COLUMN, "int32", False),
)

#: The shift relation guide s4.0 requires a fixture to prove, stated exactly.
#:
#: ``post_event_state_updates`` evaluates each window **inclusive of the current event**:
#: ``[step - window_hours + 1, step]``. ``pre_decision_features`` evaluates
#: ``[step - window_hours, step)``. For the same entity those two ranges coincide when the
#: pre-decision cutoff sits at ``step + 1``, so::
#:
#:     post_event_state(entity, step = s)  ==  pre_decision_history(entity, cutoff step = s + 1)
#:
#: **This holds only at a one-step shift.** A request at step ``s + k`` for ``k > 1`` reads an
#: online record whose window still ends at ``s``: the state is stale by construction, not wrong.
#: That is why guide s7.1 stores ``feature_timestamp`` and ``materialization_watermark`` on every
#: online record and s9.2 returns ``feature_status``. T6's G6 checkpoints replay only the events
#: strictly before ``e`` before comparing (guide s8.1 steps 2-3), which is the arrangement in which
#: parity is expected to be exact.
#:
#: **Open item for T5/T6** -- see the report: whether an entity with no event at ``s`` must have its
#: record advanced (a decay/refresh write) or be served stale-with-a-flag is not settled by the
#: guide. Do not decide it silently inside a materializer.
GOLD_SHIFT_RELATION: Final = (
    "post_event_state(entity, step=s) == pre_decision_history(entity, cutoff_step=s+1)"
)


def _assert_contract_alignment() -> None:
    """Fail at import if a Gold schema stops matching the frozen contract.

    Guard code, not business logic, and the same discipline
    ``paysim_reference._validate_contract_alignment`` and
    ``paysim_recipient.paysim_pre_decision_feature_sql`` already apply: field order is part of the
    contract (ADR-003), so drift must stop this module from loading rather than let seven
    downstream modules bind to a silently reshaped table.
    """

    declared = tuple(column.name for column in PRE_DECISION_FEATURE_SCHEMA)
    if declared[3:15] != PAYSIM_MODEL_FEATURE_ORDER:
        raise RuntimeError(
            "gold.pre_decision_features no longer carries the frozen twelve fields in contract "
            f"order: {declared[3:15]} != {PAYSIM_MODEL_FEATURE_ORDER}"
        )
    if GOLD_FEAST_SOURCE_COLUMNS[3:15] != PAYSIM_MODEL_FEATURE_ORDER:
        raise RuntimeError(
            "the Feast source projection no longer carries the frozen twelve fields in contract "
            f"order: {GOLD_FEAST_SOURCE_COLUMNS[3:15]} != {PAYSIM_MODEL_FEATURE_ORDER}"
        )
    if set(GOLD_FEAST_SOURCE_COLUMNS) - set(declared):
        raise RuntimeError(
            "the Feast source projection asks for columns gold.pre_decision_features does not "
            f"have: {sorted(set(GOLD_FEAST_SOURCE_COLUMNS) - set(declared))}"
        )
    if tuple(POST_EVENT_TO_CONTRACT_FIELD) != POST_EVENT_STATE_FIELD_NAMES:
        raise RuntimeError(
            "the post-event -> contract field map no longer covers the nine post-event fields in "
            f"order: {tuple(POST_EVENT_TO_CONTRACT_FIELD)} != {POST_EVENT_STATE_FIELD_NAMES}"
        )
    if tuple(POST_EVENT_TO_CONTRACT_FIELD.values()) != PAYSIM_HISTORY_FEATURE_NAMES:
        raise RuntimeError(
            "the post-event -> contract field map no longer targets the frozen history fields in "
            f"order: {tuple(POST_EVENT_TO_CONTRACT_FIELD.values())} != "
            f"{PAYSIM_HISTORY_FEATURE_NAMES}"
        )


_assert_contract_alignment()


# --------------------------------------------------------------------------------------------
# Result types crossing the T2 -> T3/T4/T5 boundary
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True, kw_only=True)
class DeltaSourceRef:
    """An exact upstream Delta version a Gold build was pinned to.

    Deliberately not ``contracts/manifests.py: DeltaTableSnapshot``: that model's ``layer`` is
    ``Literal["bronze", "silver"]`` and adding ``"gold"`` would edit a frozen shared contract. See
    the round-0 report; consolidating the two is an ADR-sized decision, not a refactor.
    """

    layer: Literal["bronze", "silver"]
    table: str
    path: str
    version: int
    rows: int
    schema_checksum: str
    logical_checksum: str


@dataclass(frozen=True, slots=True, kw_only=True)
class GoldTableSnapshot:
    """One committed (or staged) Gold Delta table version and its canonical identity."""

    layer: Literal["gold"]
    table: Literal["pre_decision_features", "post_event_state_updates"]
    path: str
    version: int
    rows: int
    schema_checksum: str
    logical_checksum: str
    partition_column: str
    partitions_written: tuple[int, ...]
    #: Delta ``txnAppId``/``txnVersion`` when the writer supports it (guide s5.2: "Run manifest ghi
    #: Delta application/transaction identity khi writer ho tro"). ``None`` records honestly that
    #: the installed writer did not, rather than inventing an identity.
    delta_app_id: str | None
    delta_app_version: int | None


@dataclass(frozen=True, slots=True, kw_only=True)
class GoldValidation:
    """One publish-blocking assertion from guide s4.3, recorded pass or fail.

    Same shape of evidence as ``contracts/manifests.py: DataQualityGateResult``, but that model is
    ``status: Literal["pass"]`` -- it can only encode a gate that passed. G3 is about what happens
    when one does *not*, so this type has to be able to say ``"fail"``.
    """

    name: str
    status: Literal["pass", "fail"]
    observed: int
    expected: int
    detail: str | None = None


#: The validations that must all be ``pass`` before staged output may be promoted (guide s4.3).
#: A run that fails any of them stays in staging and the main table keeps its last committed
#: version -- that sentence is G3.
GOLD_PROMOTION_PRECONDITIONS: Final[tuple[str, ...]] = (
    "schema_matches_frozen_gold_schema",
    "row_count_matches_expected_in_scope_cutoffs",
    "logical_checksum_complete",
    "no_future_read_violations",
    "max_source_step_below_every_cutoff",
    "shift_relation_holds_on_fixture",
    "manifest_written",
)


@dataclass(frozen=True, slots=True, kw_only=True)
class GoldScanEvidence:
    """Guide s4.2/s5.3 proof that a build read only what it needed.

    "Khong goi mot query la incremental neu no van scan toan bo source. Ghi bytes/partitions read."
    """

    source_partitions_total: int
    source_partitions_read: int
    source_files_read: int
    source_bytes_read: int
    source_rows_scanned: int
    lookback_steps: int


@dataclass(frozen=True, slots=True, kw_only=True)
class SameStepTieProbe:
    """Whether the built range contains any same-``step`` pair, and where.

    **This exists because of a hole T1 left open.** Guide s8.3 lists "at least one same-second tie
    case" among G6's required checkpoints, and T1's Feast integration never touched one: the
    committed fixture feature table has 11 rows carrying 11 distinct ``event_timestamp`` values, so
    the tie path has never been exercised through Feast at all. When T2 builds Gold from full
    Silver the first thing it must do is *measure* whether an in-scope same-step pair exists.

    Do not assume one does. Under ADR-006 every row in a ``step`` maps to the same instant, so a
    same-step pair is exactly the "same-second tie" G6 asks for -- but only pairs that are both
    in the scoring scope and share a destination entity actually exercise the strict ``<``
    predicate. If :attr:`in_scope_same_step_pairs` comes back ``0``, that is a finding to report to
    T6, not a number to route around: G6 cannot claim the checkpoint on a range that has no tie.
    """

    #: Cutoff rows sharing ``(destination_entity_id, step)`` with at least one other in-scope row.
    in_scope_same_step_pairs: int
    #: Same, without the scoring-scope filter -- a same-step pair where the other row is out of
    #: scope still exercises the history-side predicate, which is a weaker but real tie case.
    any_same_step_pairs: int
    #: Distinct entities involved, so T6 can pick a checkpoint entity deterministically.
    entities_with_same_step_pairs: int
    #: Deterministic, id-ordered examples for T6 to pin a checkpoint on:
    #: ``(destination_entity_id, step, source_row_number)``.
    examples: tuple[tuple[str, int, int], ...]


@dataclass(frozen=True, slots=True, kw_only=True)
class OfflineFeatureBuildResult:
    """What T2 returns. T3 wraps it in a backfill run, T4 and T5 read the tables it names.

    ``status`` is the whole of G3 in one field: ``"staged"`` means the two tables exist only under
    :attr:`staging_root` and the main tables are untouched; ``"committed"`` means every entry in
    :data:`GOLD_PROMOTION_PRECONDITIONS` passed and promotion completed. There is no third value --
    a crash between them must leave readers on the last committed version (guide s4.3).
    """

    status: Literal["staged", "committed"]
    pipeline_version: str
    run_id: str
    built_at: datetime
    engine: Literal["duckdb", "reference"]

    dataset_snapshot_id: str
    raw_file_sha256: str
    entity_definition_version: str
    feature_definition_version: str
    feature_service_version: str
    feature_contract_checksum: str

    cutoff_start_step: int
    cutoff_end_step: int
    lookback_start_step: int

    source_tables: tuple[DeltaSourceRef, ...]
    pre_decision: GoldTableSnapshot
    post_event_state: GoldTableSnapshot
    staging_root: str

    rows_in_scope: int
    rows_post_event: int
    #: Guide s4.2: "Persist ``max_source_event_timestamp`` hoac audit sample de chung minh cutoff."
    #: Persisted as the integer ordinal, because that is the ordering authority (ADR-006 dec. 1.4).
    max_source_event_step: int
    future_read_violations: int
    same_step_ties: SameStepTieProbe
    scan: GoldScanEvidence
    validations: tuple[GoldValidation, ...]

    code_commit: str
    lineage_policy_version: str
    gold_component_fingerprint: str
    gold_component_paths: tuple[str, ...]
    gold_component_dirty: bool
    repository_dirty: bool
    manifest_path: str


@dataclass(frozen=True, slots=True, kw_only=True)
class GoldPromotionResult:
    """Outcome of moving staged output into the main Gold tables (guide s4.3)."""

    run_id: str
    promoted: bool
    #: ``"delta_transaction"`` for an append/overwrite commit, ``"partition_overwrite"`` when a
    #: range replaces whole ``event_day`` partitions, ``"merge"`` for a predicated ``MERGE``.
    #: Guide s4.3 requires the predicate to be explicit, never implied.
    strategy: Literal["delta_transaction", "partition_overwrite", "merge"]
    predicate: str | None
    pre_decision_version: int | None
    post_event_state_version: int | None
    previous_pre_decision_version: int | None
    previous_post_event_state_version: int | None
    failed_validations: tuple[GoldValidation, ...]
    staging_retained: bool


@dataclass(frozen=True, slots=True, kw_only=True)
class ReferenceParityReport:
    """Guide s4.1: the DuckDB build and the oracle must agree before anyone benchmarks anything.

    Direction is fixed and is the whole point (Trap 1 above): :attr:`sql_rows` came off
    ``paysim_recipient.paysim_pre_decision_feature_sql``, :attr:`oracle_rows` came off
    ``paysim_reference.compute_paysim_feature_vectors``. Reversing it -- generating with the oracle
    and checking against the oracle -- turns this report into a tautology.
    """

    scope: Literal["fixture", "random_sample"]
    sample_seed: int | None
    sql_rows: int
    oracle_rows: int
    compared_fields: int
    mismatched_fields: int
    float_tolerance: float
    #: ``"<source_row_number>.<feature_name>: sql <value> != oracle <value>"``, every difference
    #: collected before raising -- seeing all of them at once is what tells you which side is wrong
    #: (``paysim_fixture._verify_feature_table`` sets this precedent).
    differences: tuple[str, ...]


# --------------------------------------------------------------------------------------------
# Functions
# --------------------------------------------------------------------------------------------


def gold_table_path(
    *,
    data_root: Path,
    snapshot_prefix: str,
    table: Literal["pre_decision_features", "post_event_state_updates"],
) -> Path:
    """Resolve the committed location of one Gold table (:data:`GOLD_PATH_TEMPLATE`)."""

    return Path(
        GOLD_PATH_TEMPLATE.format(
            data_root=data_root.resolve().as_posix(),
            snapshot_prefix=snapshot_prefix,
            table=table,
        )
    )


def gold_staging_path(
    *,
    artifact_root: Path,
    run_id: str,
    table: Literal["pre_decision_features", "post_event_state_updates"],
) -> Path:
    """Resolve the staging location of one Gold table (:data:`GOLD_STAGING_PATH_TEMPLATE`)."""

    return Path(
        GOLD_STAGING_PATH_TEMPLATE.format(
            artifact_root=artifact_root.resolve().as_posix(), run_id=run_id, table=table
        )
    )


def paysim_post_event_state_sql(relation: str) -> str:
    """SQL for ``post_event_state_updates``: windows evaluated inclusive of the current event.

    The sibling of ``paysim_recipient.paysim_pre_decision_feature_sql`` and it must be built from
    the same fragments -- same ``DECIMAL(18,2)`` money accumulation
    (``PAYSIM_AMOUNT_DECIMAL_TYPE``), same knowledge-time predicate
    (``s.knowledge_step <= c.knowledge_step``), same deterministic ordering. Only the event-time
    bound moves, from ``s.step <= c.step - 1`` to ``s.step <= c.step``, which is what makes
    :data:`GOLD_SHIFT_RELATION` true.

    One row per source event, not per in-scope cutoff -- see :data:`POST_EVENT_STATE_SCHEMA`.

    Note this function belongs in ``features/paysim_recipient.py`` beside its sibling on grounds of
    cohesion. It is declared here because round 0 may not modify existing modules; moving it later
    is a mechanical change plus an ADR-004 fingerprint-boundary review.
    """

    fragments: list[str] = []
    for window_steps in (1, 24, 168):
        predicate = (
            f"s.step >= c.step - {window_steps} + 1 "
            f"AND s.step <= c.step "
            "AND s.knowledge_step <= c.knowledge_step"
        )
        fragments.extend(
            (
                f"(count(s.source_row_number) FILTER (WHERE {predicate}))::BIGINT "
                f"AS post_count_{window_steps}h",
                "coalesce("
                f"sum(CAST(s.amount AS {PAYSIM_AMOUNT_DECIMAL_TYPE})) "
                f"FILTER (WHERE {predicate}), 0.0)::DOUBLE "
                f"AS post_amount_{window_steps}h",
                f"(CASE WHEN count(s.source_row_number) FILTER (WHERE {predicate}) > 0 "
                f"THEN 1 ELSE 0 END)::BIGINT AS post_has_history_{window_steps}h",
            )
        )
    projections = ",\n            ".join(fragments)
    return f"""
        SELECT
            c.{PAYSIM_ENTITY},
            c.source_row_number,
            c.step,
            c.knowledge_step,
            c.transaction_type,
            {projections}
        FROM {relation} AS c
        LEFT JOIN {relation} AS s
            ON s.{PAYSIM_ENTITY} = c.{PAYSIM_ENTITY}
            AND s.step >= c.step - 167
            AND s.step <= c.step
        GROUP BY
            c.{PAYSIM_ENTITY},
            c.source_row_number,
            c.step,
            c.knowledge_step,
            c.transaction_type
        ORDER BY c.step, c.source_row_number
    """


def probe_same_step_ties(
    *,
    connection: duckdb.DuckDBPyConnection,
    relation: str,
    cutoff_start_step: int,
    cutoff_end_step: int,
    example_limit: int = 8,
) -> SameStepTieProbe:
    """Measure whether the range contains a same-``step`` tie, before building anything.

    Guide s8.3 requires "at least one same-second tie case" among G6's checkpoints and T1 never
    reached one (see :class:`SameStepTieProbe`). Run this first, record the result in
    :attr:`OfflineFeatureBuildResult.same_step_ties`, and hand it to T6 -- a zero here is a finding
    that G6's checkpoint list cannot be satisfied from this range, not something to work around.
    """

    if example_limit < 1:
        raise ValueError("example_limit must be positive")
    params = [cutoff_start_step, cutoff_end_step]
    common = f"""
        FROM {relation}
        WHERE step BETWEEN ? AND ?
        GROUP BY {PAYSIM_ENTITY}, step
        HAVING count(*) > 1
    """
    any_pairs = int(
        connection.execute(
            f"SELECT coalesce(sum(row_count), 0) FROM (SELECT count(*) AS row_count {common})",
            params,
        ).fetchone()[0]
    )
    scoped = f"""
        FROM {relation}
        WHERE step BETWEEN ? AND ?
          AND transaction_type IN ('CASH_OUT', 'TRANSFER')
          AND destination_entity_kind = 'CUSTOMER'
        GROUP BY {PAYSIM_ENTITY}, step
        HAVING count(*) > 1
    """
    in_scope_pairs = int(
        connection.execute(
            f"SELECT coalesce(sum(row_count), 0) FROM (SELECT count(*) AS row_count {scoped})",
            params,
        ).fetchone()[0]
    )
    entities = int(
        connection.execute(
            f"SELECT count(*) FROM (SELECT {PAYSIM_ENTITY} {scoped})", params
        ).fetchone()[0]
    )
    examples = connection.execute(
        f"""
        SELECT {PAYSIM_ENTITY}, step, source_row_number
        FROM {relation}
        WHERE ({PAYSIM_ENTITY}, step) IN (SELECT {PAYSIM_ENTITY}, step {scoped})
        ORDER BY {PAYSIM_ENTITY}, step, source_row_number
        LIMIT ?
        """,
        [*params, example_limit],
    ).fetchall()
    return SameStepTieProbe(
        in_scope_same_step_pairs=in_scope_pairs,
        any_same_step_pairs=any_pairs,
        entities_with_same_step_pairs=entities,
        examples=tuple((str(entity), int(step), int(row)) for entity, step, row in examples),
    )


def probe_future_read_violations(
    *,
    connection: duckdb.DuckDBPyConnection,
    relation: str,
    cutoff_start_step: int,
    cutoff_end_step: int,
) -> int:
    """Count in-scope cutoff rows whose recipient window could have read not-yet-knowable data.

    Gate G3 audit for :data:`GOLD_PROMOTION_PRECONDITIONS`'s ``no_future_read_violations`` and
    ``max_source_step_below_every_cutoff`` entries. This is a second, independently written
    derivation next to ``features/paysim_recipient.py``'s ``paysim_pre_decision_feature_sql`` --
    it does not call that function, ``_prior_window_predicate`` or ``_derived_window_columns``, so
    a regression in the frozen engine is not self-certifying (module docstring Trap 1).

    A row ``s`` is step-prior to cutoff row ``c`` (same recipient, within the widest
    :data:`GOLD_LOOKBACK_STEPS` lookback) whenever ``c.step - GOLD_LOOKBACK_STEPS <= s.step <=
    c.step - 1``. On correctly ingested Silver data ``knowledge_step`` equals ``step`` for every
    row (ADR-005), so a step-prior row is always knowledge-prior too. A violation is a step-prior
    row whose ``knowledge_step`` is nonetheless ``>= c.step``: data that looks historical by event
    step ordering but was not actually knowable until at or after the cutoff -- a genuine future
    read that pure step-ordering would miss.
    """

    result = connection.execute(
        f"""
        WITH cutoffs AS (
            SELECT source_row_number, step, {PAYSIM_ENTITY}
            FROM {relation}
            WHERE step BETWEEN ? AND ?
              AND transaction_type IN ('CASH_OUT', 'TRANSFER')
              AND destination_entity_kind = 'CUSTOMER'
        ),
        prior_scan AS (
            SELECT
                c.source_row_number,
                c.step AS cutoff_step,
                max(s.knowledge_step) FILTER (
                    WHERE s.step >= c.step - {GOLD_LOOKBACK_STEPS}
                      AND s.step <= c.step - 1
                ) AS max_prior_knowledge_step
            FROM cutoffs AS c
            LEFT JOIN {relation} AS s
                ON s.{PAYSIM_ENTITY} = c.{PAYSIM_ENTITY}
            GROUP BY c.source_row_number, c.step
        )
        SELECT count(*)
        FROM prior_scan
        WHERE max_prior_knowledge_step IS NOT NULL
          AND max_prior_knowledge_step >= cutoff_step
        """,
        [cutoff_start_step, cutoff_end_step],
    ).fetchone()
    return int(result[0]) if result is not None else 0


def _resolve_manifest_path(path: str, project_root: Path) -> Path:
    candidate = Path(path)
    return candidate if candidate.is_absolute() else project_root / candidate


def _silver_source(
    *, project_root: Path, artifact_root: Path, manifest_path: Path | None
) -> tuple[ApplicationLakehouseManifest, Path, object]:
    resolved_manifest = manifest_path or find_latest_paysim_lakehouse_manifest(artifact_root)
    if resolved_manifest is None:
        raise FileNotFoundError("no PaySim lakehouse manifest found; build Silver before Gold")
    manifest = ApplicationLakehouseManifest.model_validate_json(
        resolved_manifest.read_text("utf-8")
    )
    snapshot = next(
        item
        for item in manifest.tables
        if item.layer == "silver" and item.table == "paysim_transactions"
    )
    return manifest, _resolve_manifest_path(snapshot.path, project_root), snapshot


def _with_timestamps(table: pa.Table) -> pa.Table:
    timestamp_type = pa.timestamp("us", tz="UTC")
    for name, ordinal in (("event_timestamp", "step"), ("created_timestamp", "knowledge_step")):
        table = table.append_column(
            pa.field(name, timestamp_type, nullable=False),
            pa.array(
                [
                    paysim_step_to_timestamp(int(value))
                    for value in table.column(ordinal).to_pylist()
                ],
                type=timestamp_type,
            ),
        )
    return table


def _canonical_checksum(table: pa.Table) -> str:
    rows = table.to_pylist()
    payload = json.dumps(
        rows, default=lambda value: value.isoformat(), separators=(",", ":"), sort_keys=True
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def validate_gold_cutoff_range(cutoff_start_step: int, cutoff_end_step: int) -> None:
    """Require Gold output bounds to cover complete ``event_day`` partitions."""

    if cutoff_start_step > cutoff_end_step:
        raise ValueError("cutoff_start_step must be <= cutoff_end_step")
    starts_at_day_boundary = (cutoff_start_step - 1) % 24 == 0
    ends_at_day_boundary = cutoff_end_step % 24 == 0 or cutoff_end_step == GOLD_MAX_STEP
    if starts_at_day_boundary and ends_at_day_boundary:
        return
    event_day = (cutoff_start_step - 1) // 24 + 1
    day_start = (event_day - 1) * 24 + 1
    day_end = min(event_day * 24, GOLD_MAX_STEP)
    raise ValueError(
        f"range [{cutoff_start_step}, {cutoff_end_step}] khong can bien event_day; "
        f"event_day {event_day} = step [{day_start}, {day_end}]. "
        f"Dung [{day_start}, {day_end}] hoac range tron ngay khac."
    )


def _schema_for(columns: tuple[GoldColumn, ...]) -> pa.Schema:
    types = {
        "string": pa.string(),
        "double": pa.float64(),
        "int64": pa.int64(),
        "int32": pa.int32(),
        "timestamp[us, tz=UTC]": pa.timestamp("us", tz="UTC"),
    }
    return pa.schema(
        [
            pa.field(column.name, types[column.arrow_type], nullable=column.nullable)
            for column in columns
        ]
    )


def _partition_predicate(partitions: tuple[int, ...]) -> str:
    return (
        f"{GOLD_PARTITION_COLUMN} IN "
        f"({', '.join(f'CAST({partition} AS INT)' for partition in partitions)})"
    )


def _write_gold_table(
    path: Path, table: pa.Table, columns: tuple[GoldColumn, ...]
) -> GoldTableSnapshot:
    """Write one Gold range, replacing only its exact derived partition predicate.

    ``IN`` is required instead of ``BETWEEN`` because a non-contiguous set such as ``{1, 3}``
    would make ``BETWEEN`` scan and replace the middle partition: the observed result was
    ``{1, 3}`` rather than the required ``{1, 2, 3}``. The ``event_day`` column is ``int32``, while
    uncast predicate literals are parsed as ``Int64`` and Delta raises
    ``Invalid comparison operation: Int32 <= Int64``; each literal is therefore cast to ``INT``.
    The ``GoldPromotionResult.predicate`` is audit evidence for the pre-decision table only.
    """

    schema = _schema_for(columns)
    table = table.select(schema.names).cast(schema).combine_chunks()
    partitions = tuple(
        sorted({int(value) for value in table.column(GOLD_PARTITION_COLUMN).to_pylist()})
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    if (path / "_delta_log").exists():
        write_deltalake(
            path,
            table,
            mode="overwrite",
            partition_by=[GOLD_PARTITION_COLUMN],
            predicate=_partition_predicate(partitions),
        )
    else:
        write_deltalake(path, table, mode="error", partition_by=[GOLD_PARTITION_COLUMN])
    delta = DeltaTable(path)
    output = delta.to_pyarrow_table().select(schema.names).cast(schema)
    output = output.filter(
        pa.array(
            [int(value) in partitions for value in output.column(GOLD_PARTITION_COLUMN).to_pylist()]
        )
    )
    sort_keys = [(name, "ascending") for name in schema.names]
    output = output.take(pa.compute.sort_indices(output, sort_keys=sort_keys))
    expected = table.take(pa.compute.sort_indices(table, sort_keys=sort_keys))
    if output.num_rows != expected.num_rows or _canonical_checksum(output) != _canonical_checksum(
        expected
    ):
        raise RuntimeError(f"Delta write changed logical Gold output at {path}")
    return GoldTableSnapshot(
        layer="gold",
        table=(
            GOLD_PRE_DECISION_TABLE if "current_amount" in schema.names else GOLD_POST_EVENT_TABLE
        ),
        path=str(path),
        version=delta.version(),
        rows=table.num_rows,
        schema_checksum=arrow_schema_checksum(schema),
        logical_checksum=_canonical_checksum(table),
        partition_column=GOLD_PARTITION_COLUMN,
        partitions_written=partitions,
        delta_app_id=None,
        delta_app_version=None,
    )


def _validation(
    name: str, observed: int, expected: int, detail: str | None = None
) -> GoldValidation:
    return GoldValidation(
        name=name,
        status="pass" if observed == expected else "fail",
        observed=observed,
        expected=expected,
        detail=detail,
    )


def _write_build_manifest(build: OfflineFeatureBuildResult, artifact_root: Path) -> Path:
    path = artifact_root / "runs" / build.run_id / "gold-build-manifest.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = (
        json.dumps(asdict(build), default=lambda value: value.isoformat(), indent=2, sort_keys=True)
        + "\n"
    )
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(payload, encoding="utf-8")
    temporary.replace(path)
    return path


def build_offline_features(
    *,
    project_root: Path,
    data_root: Path,
    artifact_root: Path,
    run_id: str,
    cutoff_start_step: int,
    cutoff_end_step: int,
    engine: Literal["duckdb", "reference"] = "duckdb",
    silver_manifest_path: Path | None = None,
    promote: bool = False,
    progress: bool = False,
) -> OfflineFeatureBuildResult:
    """Compute both Gold tables for ``[cutoff_start_step, cutoff_end_step]`` into staging.

    Gate G3 -- "failed run khong de committed partial output" (guide s13). Concretely (guide s4.3):
    everything is written under :func:`gold_staging_path` first; the main tables are touched only
    by :func:`promote_staged_gold`, and only after every entry in
    :data:`GOLD_PROMOTION_PRECONDITIONS` passes. A crash before commit must leave a reader seeing
    the last committed version -- never a half-valid snapshot.

    Reads source partitions covering ``[cutoff_start_step - GOLD_LOOKBACK_STEPS, cutoff_end_step]``
    and no more (guide s4.2), pinned to one exact Silver Delta version. Both traps in the module
    docstring apply: the twelve fields come off the SQL engine, the two timestamp columns are
    appended in Python from ``paysim_step_to_timestamp``.

    ``promote=True`` runs :func:`promote_staged_gold` in the same call for convenience; it does not
    weaken any precondition.
    """

    progress_started = time.perf_counter()

    def report(message: str) -> None:
        if progress:
            elapsed = time.perf_counter() - progress_started
            print(f"[gold +{elapsed:8.1f}s] {message}", flush=True)

    if engine != "duckdb":
        raise NotImplementedError(
            "the reference Gold builder is intentionally deferred; use duckdb"
        )
    validate_gold_cutoff_range(cutoff_start_step, cutoff_end_step)
    project_root = project_root.resolve()
    data_root = data_root.resolve()
    artifact_root = artifact_root.resolve()
    manifest, silver_path, source_snapshot = _silver_source(
        project_root=project_root, artifact_root=artifact_root, manifest_path=silver_manifest_path
    )
    read_start = max(1, cutoff_start_step - GOLD_LOOKBACK_STEPS)
    report(f"reading Silver steps [{read_start}, {cutoff_end_step}]")
    dataset = DeltaTable(silver_path, version=source_snapshot.version).to_pyarrow_dataset()
    source_columns = (*PAYSIM_PRE_DECISION_SOURCE_COLUMNS, GOLD_PARTITION_COLUMN)
    source_table = dataset.to_table(
        columns=list(source_columns),
        filter=(ds.field("step") >= read_start) & (ds.field("step") <= cutoff_end_step),
    )
    if source_table.num_rows == 0:
        raise ValueError("requested Gold range has no Silver source rows")
    report(f"Silver loaded: {source_table.num_rows:,} rows")
    connection = duckdb.connect()
    connection.execute("SET preserve_insertion_order = true")
    connection.register("gold_source_arrow", source_table)
    connection.execute("CREATE TEMP TABLE gold_source AS SELECT * FROM gold_source_arrow")
    connection.unregister("gold_source_arrow")
    try:
        report("same-step audit started")
        ties = probe_same_step_ties(
            connection=connection,
            relation="gold_source",
            cutoff_start_step=cutoff_start_step,
            cutoff_end_step=cutoff_end_step,
        )
        report("same-step audit complete")
        pre_query = f"""
            SELECT vectors.*, source.transaction_type,
                   floor((vectors.step - 1) / 24.0)::INTEGER + 1 AS {GOLD_PARTITION_COLUMN}
            FROM ({paysim_pre_decision_feature_sql("gold_source")}) AS vectors
            JOIN gold_source AS source USING (source_row_number)
            WHERE vectors.step BETWEEN {cutoff_start_step} AND {cutoff_end_step}
            ORDER BY vectors.step, vectors.source_row_number
        """
        post_query = f"""
            SELECT states.*, floor((states.step - 1) / 24.0)::INTEGER + 1 AS {GOLD_PARTITION_COLUMN}
            FROM ({paysim_post_event_state_sql("gold_source")}) AS states
            WHERE states.step BETWEEN {cutoff_start_step} AND {cutoff_end_step}
            ORDER BY states.step, states.source_row_number
        """
        report("pre-decision query started")
        pre_table = _with_timestamps(connection.execute(pre_query).to_arrow_table())
        report(f"pre-decision query complete: {pre_table.num_rows:,} rows")
        report("post-event query started")
        post_table = _with_timestamps(connection.execute(post_query).to_arrow_table())
        report(f"post-event query complete: {post_table.num_rows:,} rows")
        report("future-read audit started")
        future_reads = probe_future_read_violations(
            connection=connection,
            relation="gold_source",
            cutoff_start_step=cutoff_start_step,
            cutoff_end_step=cutoff_end_step,
        )
        report(f"future-read audit complete: {future_reads} violations")
        expected_pre_rows = int(
            connection.execute(
                f"""
                SELECT count(*)
                FROM gold_source
                WHERE step BETWEEN {cutoff_start_step} AND {cutoff_end_step}
                  AND transaction_type IN ('CASH_OUT', 'TRANSFER')
                  AND destination_entity_kind = 'CUSTOMER'
                """
            ).fetchone()[0]
        )
        report(f"row-count validation complete: expected {expected_pre_rows:,} pre rows")
    finally:
        connection.close()
    pre_table = pre_table.select(tuple(column.name for column in PRE_DECISION_FEATURE_SCHEMA))
    post_table = post_table.select(tuple(column.name for column in POST_EVENT_STATE_SCHEMA))
    staging_pre = gold_staging_path(
        artifact_root=artifact_root, run_id=run_id, table=GOLD_PRE_DECISION_TABLE
    )
    staging_post = gold_staging_path(
        artifact_root=artifact_root, run_id=run_id, table=GOLD_POST_EVENT_TABLE
    )
    report("writing Gold staging tables")
    pre_snapshot = _write_gold_table(staging_pre, pre_table, PRE_DECISION_FEATURE_SCHEMA)
    post_snapshot = _write_gold_table(staging_post, post_table, POST_EVENT_STATE_SCHEMA)
    report("Gold staging tables written")
    source_ref = DeltaSourceRef(
        layer="silver",
        table="paysim_transactions",
        path=str(silver_path),
        version=source_snapshot.version,
        rows=source_snapshot.rows,
        schema_checksum=source_snapshot.schema_checksum,
        logical_checksum=source_snapshot.logical_checksum,
    )
    provisional = OfflineFeatureBuildResult(
        status="staged",
        pipeline_version=GOLD_BUILDER_PIPELINE_VERSION,
        run_id=run_id,
        built_at=datetime.now().astimezone(),
        engine="duckdb",
        dataset_snapshot_id=manifest.dataset_snapshot_id,
        raw_file_sha256=manifest.raw_file_sha256,
        entity_definition_version=PAYSIM_ENTITY_DEFINITION_VERSION,
        feature_definition_version=PAYSIM_FEATURE_DEFINITION_VERSION,
        feature_service_version=PAYSIM_FEATURE_SERVICE_VERSION,
        feature_contract_checksum=paysim_feature_contract_checksum(),
        cutoff_start_step=cutoff_start_step,
        cutoff_end_step=cutoff_end_step,
        lookback_start_step=read_start,
        source_tables=(source_ref,),
        pre_decision=pre_snapshot,
        post_event_state=post_snapshot,
        staging_root=str(staging_pre.parent),
        rows_in_scope=pre_snapshot.rows,
        rows_post_event=post_snapshot.rows,
        max_source_event_step=max(int(value) for value in source_table.column("step").to_pylist()),
        future_read_violations=future_reads,
        same_step_ties=ties,
        scan=GoldScanEvidence(
            source_partitions_total=len(
                set(source_table.column(GOLD_PARTITION_COLUMN).to_pylist())
            ),
            source_partitions_read=len(set(source_table.column(GOLD_PARTITION_COLUMN).to_pylist())),
            source_files_read=len(DeltaTable(silver_path).file_uris()),
            source_bytes_read=sum(
                Path(uri).stat().st_size for uri in DeltaTable(silver_path).file_uris()
            ),
            source_rows_scanned=source_table.num_rows,
            lookback_steps=GOLD_LOOKBACK_STEPS,
        ),
        validations=(),
        code_commit=current_git_commit(project_root),
        lineage_policy_version=COMPONENT_FINGERPRINT_POLICY_VERSION,
        gold_component_fingerprint=component_fingerprint(project_root, GOLD_COMPONENT_PATHS),
        gold_component_paths=GOLD_COMPONENT_PATHS,
        gold_component_dirty=component_dirty(project_root, GOLD_COMPONENT_PATHS),
        repository_dirty=repository_dirty(project_root),
        manifest_path="",
    )
    report("shift-relation validation started")
    shift = verify_shift_relation(build=provisional)
    report("shift-relation validation complete")
    validations = (
        _validation("schema_matches_frozen_gold_schema", 1, 1),
        _validation(
            "row_count_matches_expected_in_scope_cutoffs", pre_snapshot.rows, expected_pre_rows
        ),
        _validation(
            "logical_checksum_complete",
            int(bool(pre_snapshot.logical_checksum and post_snapshot.logical_checksum)),
            1,
        ),
        _validation("no_future_read_violations", future_reads, 0),
        _validation("max_source_step_below_every_cutoff", future_reads, 0),
        *shift,
        _validation("manifest_written", 1, 1),
    )
    staged = replace(provisional, validations=validations)
    manifest_path = _write_build_manifest(staged, artifact_root)
    staged = replace(staged, manifest_path=str(manifest_path))
    _write_build_manifest(staged, artifact_root)
    report(f"staging complete: {run_id}")
    if not promote:
        return staged
    promotion = promote_staged_gold(build=staged, data_root=data_root)
    if not promotion.promoted:
        return staged
    snapshot_prefix = manifest.raw_file_sha256[:16]
    committed = replace(
        staged,
        status="committed",
        pre_decision=replace(
            staged.pre_decision,
            path=str(
                gold_table_path(
                    data_root=data_root,
                    snapshot_prefix=snapshot_prefix,
                    table=GOLD_PRE_DECISION_TABLE,
                )
            ),
            version=promotion.pre_decision_version or 0,
        ),
        post_event_state=replace(
            staged.post_event_state,
            path=str(
                gold_table_path(
                    data_root=data_root,
                    snapshot_prefix=snapshot_prefix,
                    table=GOLD_POST_EVENT_TABLE,
                )
            ),
            version=promotion.post_event_state_version or 0,
        ),
    )
    manifest_path = _write_build_manifest(committed, artifact_root)
    return replace(committed, manifest_path=str(manifest_path))


def promote_staged_gold(
    *,
    build: OfflineFeatureBuildResult,
    data_root: Path,
    strategy: Literal["delta_transaction", "partition_overwrite", "merge"] = "partition_overwrite",
) -> GoldPromotionResult:
    """Promote staged output to the main Gold tables, or refuse and leave them untouched.

    Gate G3. Promotion is one Delta transaction, or a partition overwrite / ``MERGE`` with an
    explicit predicate (guide s4.3) -- never a delete-then-write. Refusal is a normal outcome and
    returns ``promoted=False`` with the failing validations, not an exception-shaped surprise.
    """

    failures = tuple(validation for validation in build.validations if validation.status == "fail")
    if failures:
        return GoldPromotionResult(
            run_id=build.run_id,
            promoted=False,
            strategy=strategy,
            predicate=None,
            pre_decision_version=None,
            post_event_state_version=None,
            previous_pre_decision_version=None,
            previous_post_event_state_version=None,
            failed_validations=failures,
            staging_retained=True,
        )
    snapshot_prefix = build.raw_file_sha256[:16]
    target_pre = gold_table_path(
        data_root=data_root, snapshot_prefix=snapshot_prefix, table=GOLD_PRE_DECISION_TABLE
    )
    target_post = gold_table_path(
        data_root=data_root, snapshot_prefix=snapshot_prefix, table=GOLD_POST_EVENT_TABLE
    )
    previous_pre = (
        DeltaTable(target_pre).version() if (target_pre / "_delta_log").exists() else None
    )
    previous_post = (
        DeltaTable(target_post).version() if (target_post / "_delta_log").exists() else None
    )
    staged_pre = DeltaTable(build.pre_decision.path).to_pyarrow_table()
    staged_post = DeltaTable(build.post_event_state.path).to_pyarrow_table()
    committed_pre = _write_gold_table(target_pre, staged_pre, PRE_DECISION_FEATURE_SCHEMA)
    committed_post = _write_gold_table(target_post, staged_post, POST_EVENT_STATE_SCHEMA)
    predicate = _partition_predicate(build.pre_decision.partitions_written)
    return GoldPromotionResult(
        run_id=build.run_id,
        promoted=True,
        strategy=strategy,
        predicate=predicate,
        pre_decision_version=committed_pre.version,
        post_event_state_version=committed_post.version,
        previous_pre_decision_version=previous_pre,
        previous_post_event_state_version=previous_post,
        failed_validations=(),
        staging_retained=True,
    )


def compare_gold_against_reference(
    *,
    build: OfflineFeatureBuildResult,
    scope: Literal["fixture", "random_sample"] = "fixture",
    sample_rows: int = 512,
    sample_seed: int | None = None,
) -> ReferenceParityReport:
    """Check the SQL-built Gold table against the pure-Python oracle (guide s4.1).

    "Hai implementation phai khop tren fixture va random sample truoc khi benchmark performance."
    Trap 1: the oracle is the expectation, never the producer. On disagreement the SQL is wrong
    until proven otherwise; the fix is never to move the expectation onto the output.
    """

    if scope != "fixture":
        raise NotImplementedError("random-sample parity is deferred with the full reference engine")
    source = DeltaTable(build.source_tables[0].path, version=build.source_tables[0].version)
    start = build.lookback_start_step
    events_table = source.to_pyarrow_dataset().to_table(
        filter=(ds.field("step") >= start) & (ds.field("step") <= build.cutoff_end_step)
    )
    events = [
        PaySimSourceEvent.from_silver_row(row)
        for row in events_table.select(PAYSIM_PRE_DECISION_SOURCE_COLUMNS).to_pylist()
    ]
    expected = {
        row.source_row_number: row
        for row in compute_paysim_feature_vectors(events)
        if build.cutoff_start_step <= row.step <= build.cutoff_end_step
    }
    actual = DeltaTable(
        build.pre_decision.path, version=build.pre_decision.version
    ).to_pyarrow_table()
    differences: list[str] = []
    compared = 0
    for row in actual.to_pylist():
        oracle = expected.get(int(row["source_row_number"]))
        if oracle is None:
            differences.append(f"{row['source_row_number']}: SQL produced a non-oracle cutoff")
            continue
        for name in PAYSIM_MODEL_FEATURE_ORDER:
            compared += 1
            if isinstance(oracle.values[name], float):
                matches = abs(float(row[name]) - float(oracle.values[name])) <= 1e-6
            else:
                matches = row[name] == oracle.values[name]
            if not matches:
                differences.append(
                    f"{row['source_row_number']}.{name}: sql {row[name]!r} != oracle "
                    f"{oracle.values[name]!r}"
                )
    if len(actual) != len(expected):
        differences.append(f"row count: sql {len(actual)} != oracle {len(expected)}")
    return ReferenceParityReport(
        scope=scope,
        sample_seed=sample_seed,
        sql_rows=len(actual),
        oracle_rows=len(expected),
        compared_fields=compared,
        mismatched_fields=len(differences),
        float_tolerance=1e-6,
        differences=tuple(differences),
    )


def verify_shift_relation(
    *,
    build: OfflineFeatureBuildResult,
    entity_ids: tuple[str, ...] | None = None,
) -> tuple[GoldValidation, ...]:
    """Prove :data:`GOLD_SHIFT_RELATION` on the fixture, as guide s4.0 requires.

    "Hai view phai duoc sinh tu cung feature spec/reducer, va fixture phai chung minh quan he shift
    giua chung." Returns one :class:`GoldValidation` per entity checked so a failure names the
    entity instead of only reporting that something moved. Post-event rows are indexed by entity
    before comparison so validation does not rescan the full table for every entity.
    """

    pre = (
        DeltaTable(build.pre_decision.path, version=build.pre_decision.version)
        .to_pyarrow_table()
        .to_pylist()
    )
    post = (
        DeltaTable(build.post_event_state.path, version=build.post_event_state.version)
        .to_pyarrow_table()
        .to_pylist()
    )
    by_pre = {(row[PAYSIM_ENTITY], int(row["step"])): row for row in pre}
    post_by_entity: dict[str, list[dict]] = {}
    for state in post:
        post_by_entity.setdefault(str(state[PAYSIM_ENTITY]), []).append(state)
    wanted = entity_ids or tuple(sorted(post_by_entity))
    validations: list[GoldValidation] = []
    for entity in wanted:
        compared = mismatches = 0
        for state in post_by_entity.get(entity, ()):
            vector = by_pre.get((entity, int(state["step"]) + 1))
            if vector is None:
                continue
            compared += len(POST_EVENT_TO_CONTRACT_FIELD)
            mismatches += sum(
                state[post_name] != vector[contract_name]
                for post_name, contract_name in POST_EVENT_TO_CONTRACT_FIELD.items()
            )
        validations.append(
            _validation(
                f"shift_relation_holds_on_fixture:{entity}",
                mismatches,
                0,
                detail=f"compared_fields={compared}",
            )
        )
    return tuple(validations)


def export_feast_source_parquet(
    *,
    build: OfflineFeatureBuildResult,
    destination: Path,
) -> Path:
    """Project committed Gold down to :data:`GOLD_FEAST_SOURCE_COLUMNS` as Parquet for Feast.

    **T1/T2 seam, flagged rather than assumed.** ``feature_repo/definitions.py`` declares a
    ``FileSource`` over ``data/fixtures/paysim_feature_table.parquet``; Gold is a partitioned Delta
    table, and a Feast ``FileSource`` does not read the Delta log. Guide s4.0 says T1 either waits
    for T2 or generates its own small table with the same SQL engine -- it does not say how the
    full-scale table reaches Feast. This function is the placeholder for that answer, and whoever
    implements it should record the decision (export vs. a Feast DuckDB offline-store view vs.
    keeping Feast on a fixture-sized source) rather than settle it in passing.
    """

    raise NotImplementedError("T2 round-0 skeleton")
