"""T3 -- backfill state machine, idempotency and run manifests (guide s5; gate G2)."""

from pit_fintech.backfill.records import (
    BACKFILL_IDEMPOTENCY_KEY_POLICY_VERSION,
    BackfillCounts,
    BackfillError,
    BackfillMode,
    BackfillRerunComparison,
    BackfillResumeAction,
    BackfillRunRecord,
    BackfillScanEvidence,
    BackfillState,
    BackfillTimings,
    LateArrivalCorrectionReport,
    MaterializationReuse,
    PartitionChecksum,
    backfill_idempotency_key,
)
from pit_fintech.backfill.state_machine import (
    BackfillPlan,
    IdempotencyResolution,
    cleanup_staging,
    compare_reruns,
    execute_backfill,
    find_runs_by_idempotency_key,
    inject_late_arrival_correction,
    load_run_manifest,
    plan_backfill,
    record_from_build,
    resolve_idempotent_run,
    transition,
    write_run_manifest,
)

__all__ = [
    "BACKFILL_IDEMPOTENCY_KEY_POLICY_VERSION",
    "BackfillCounts",
    "BackfillError",
    "BackfillMode",
    "BackfillPlan",
    "BackfillRerunComparison",
    "BackfillResumeAction",
    "BackfillRunRecord",
    "BackfillScanEvidence",
    "BackfillState",
    "BackfillTimings",
    "IdempotencyResolution",
    "LateArrivalCorrectionReport",
    "MaterializationReuse",
    "PartitionChecksum",
    "backfill_idempotency_key",
    "cleanup_staging",
    "compare_reruns",
    "execute_backfill",
    "find_runs_by_idempotency_key",
    "inject_late_arrival_correction",
    "load_run_manifest",
    "plan_backfill",
    "record_from_build",
    "resolve_idempotent_run",
    "transition",
    "write_run_manifest",
]
